### ISSUE TITLE
Can't change ranking players

### ISSUE THREAD

**Issue by MikolajSzumigalski** [johnridesabike/coronate#10]
I find small bug. When I try add new user to tournament I can't change his ranking. When I try change ranking input, input above is changing.

![Zrzut ekranu 2020-05-30 o 17 06 31](https://user-images.githubusercontent.com/17854328/83331721-1b999480-a298-11ea-985a-008db9c0a4bc.png)

In the other hand this app is great! I try write mobile chess tournament app in React Native, but I can't write swiss pairing algorithm...

**Comment by johnridesabike** [comment]
This should be fixed now in https://github.com/johnridesabike/coronate/commit/9c062af90709ee4fdf3d9a5bf43e250335c51327

Figuring out the Swiss pairing was one of the trickier parts of making this. You can see a lot of the logic for it here: https://github.com/johnridesabike/coronate/blob/master/src/Data/Data_Pairing.re Some of the code is still a bit messy, but the basic idea is that you need to get a list of every possible pairing, rate how ideal that pairing is, and then use the [blossom algorithm](https://github.com/johnridesabike/re-blossom) to get the result.
