### ISSUE TITLE
running `npm run re:watch`

### ISSUE THREAD

**Issue by idkjs** [johnridesabike/coronate#15]
Hello brother.

You not in the docs that you dont have to run `npm run re:watch` if using vscode.

I am not getting that experience after installing the deps.

This is what I am seeing here and generally. 

![Screen Shot 2020-09-25 at 5 52 42 PM](https://user-images.githubusercontent.com/2370391/94319134-fc65f780-ff57-11ea-9f6b-d0b8e14a5d8f.png)

I figured I would ask since you seem to have a hold on it.

Here is the entire screen. Note that you can't find bsb at the bottom and that files are not compiled obviously.

![Screen Shot 2020-09-25 at 5 55 17 PM](https://user-images.githubusercontent.com/2370391/94319328-5c5c9e00-ff58-11ea-9e07-51a2c9f7de3c.png)

Do you have any guidance you might share?

Thank you.

**Comment by johnridesabike** [comment]
This depends on your VS Code configuration. I believe that the Reason extension will automatically compile `.re` files by default, but that can be turned off.

I myself haven’t used the VS Code Reason extension for a while, and I typically run `re:watch` manually anyway. It’s possible that the README is outdated on that particular topic.

(Sorry for the late response. I somehow missed this when going through my GitHub notifications a while ago.)
