### ISSUE TITLE
Thanks for making this

### ISSUE THREAD

**Issue by StanleyGoldman** [johnridesabike/coronate#17]
Myself and a few other engineers working at GitHub have been using this to run a chess tournament for ourselves.
I wanted to say thanks. 🥇 🏆 ✨

**Comment by johnridesabike** [comment]
Thanks! I'm glad you appreciate it.

**Comment by johnridesabike** [comment]
For anyone reading this who is interested, I've added a new way to show your appreciation:

<a href="https://www.buymeacoffee.com/johnridesabike" target="_blank">
  <img
    src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png"
    alt="Buy Me A Coffee"
    height="60"
    width="217"
    style="height: 60px !important;width: 217px !important;" />
</a>

(Only if you want to. Coronate is always free 😁)

**Comment by StanleyGoldman** [comment]
Enjoy the coffee.
