### ISSUE TITLE
Invalid font files are emitted by Webpack.

### ISSUE THREAD

**Issue by tomkao** [johnridesabike/coronate#73]
The following error message is logged in the Firefox console when opening up the website.

`downloadable font: rejected by sanitizer (font-family: "Fira Sans" style:normal weight:200 stretch:100 src index:2) source: https://coronate.netlify.app/static/media/fira-sans-latin-200.39cc619f2ee02ae0a912.woff2`
`downloadable font: rejected by sanitizer (font-family: "Fira Sans" style:normal weight:200 stretch:100 src index:3) source: https://coronate.netlify.app/static/media/fira-sans-latin-200.53e088d7c8424bf2e605.woff`

On closer inspection, this could be because Webpack emits text files rather than font files. It may be because the file-loader module was [deprecated](https://github.com/webpack-contrib/file-loader#file-loader) in Webpak v5.

**Comment by johnridesabike** [comment]
Thanks for the report! I believe that this webpack configuration is due for an upgrade in some other things too. I'll see how easy this is to fix.
