### ISSUE TITLE
FR: custom names for White/Black

### ISSUE THREAD

**Issue by phoe** [johnridesabike/coronate#89]
I'm using Coronate to record [Arimaa](https://en.wikipedia.org/wiki/Arimaa) tournaments. This game has Gold and Silver instead of White and Black, which is a source of confusion for players when the Coronate pairing page is displayed; my feature request is to make these names configurable, so Arimaa or shogi (sente/gote) or xiangqi (red/black) naming can be used instead.

**Comment by johnridesabike** [comment]
Thanks for the suggestion! This shouldn't be too hard to add. I'll put it on the to-do list.
