### ISSUE TITLE
have time for improvements ?

### ISSUE THREAD

**Issue by tissatussa** [johnridesabike/coronate#93]
It would be great if you had some time to work on this program in the near future, could you implement the alphabetical order of the player names ? Regarding the current version, this is the only main shortcoming while using Coronate : selecting players for a next round can be tedious when the list is long. Is the sorting really hard to do ? On my first club evening next year (Januari 8th) i will again be using Coronate for our Rapid Competition.

**Comment by johnridesabike** [comment]
I'll see what I'm able to do in the next week or so!

**Comment by tissatussa** [comment]
i wish you the best, have a good time !

![daltons2](https://github.com/johnridesabike/coronate/assets/1109281/be7e7980-cda0-4c72-ab05-7bb66b7aebc8)

**Comment by johnridesabike** [comment]
I just added a few minor features, including sorting the player lists!

**Comment by tissatussa** [comment]
@johnridesabike : great ! I will test it soon, and report.

**Comment by tissatussa** [comment]
i think some more improvements could be made, but Coronate works fine now!
